apiVersion: apps/v1
kind: Deployment
metadata:
  name: otel-dice-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: otel-dice
  template:
    metadata:
      labels:
        app: otel-dice
    spec:
      containers:
        - name: opentelemetry-collector
          image: otel/opentelemetry-collector:latest
          ports:
            - containerPort: 4317  
            - containerPort: 4318  
            - containerPort: 9464  
          volumeMounts:
            - name: config-volume
              mountPath: /etc/otelcol/config.yaml
              subPath: config.yaml
            - name: otel-logs-volume
              mountPath: /var/log
          env:
            - name: OTEL_FEATURES
              value: "-component.UseLocalHostAsDefaultHost"
        - name: dice-otl
          image: jorgepuerta00/my-node-app:latest
          ports:
            - containerPort: 8080
          volumeMounts:
            - name: otel-logs-volume
              mountPath: /var/log
      volumes:
        - name: config-volume
          configMap:
            name: otl-configmap
        - name: otel-logs-volume
          emptyDir: {}
