apiVersion: v1
kind: Service
metadata:
  name: otel-dice
  namespace: otlp
spec:
  selector:
    app: otel-dice
  ports:
    - name: grpc
      port: 4317
      targetPort: 4317
    - name: http
      port: 4318
      targetPort: 4318
    - name: prometheus
      port: 9464
      targetPort: 9464
    - name: dice
      port: 5000
      targetPort: 5000
  type: LoadBalancer
