apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
  namespace: logging
  labels:
    app: prometheus
data:
  prometheus.yml: |
    global:
      scrape_interval: 15s

    scrape_configs:
      - job_name: otel-dice
        scrape_interval: 5s
        static_configs:
          - targets: ['otel-dice.otlp.svc.cluster.local:9464']
