config:
  server:
    http_listen_port: 9080
    grpc_listen_port: 0

  positions:
    filename: /run/promtail/positions.yaml

  clients:
    - url: http://loki-gateway.logging.svc.cluster.local:80/loki/api/v1/push

  scrape_configs:
    - job_name: 'system'
      static_configs:
        - targets: ['localhost']
          labels:
            job: varlogs
            __path__: /var/log/**/*.log

    - job_name: 'kubernetes-pods'
      kubernetes_sd_configs:
        - role: pod
      relabel_configs:
        - source_labels: [__meta_kubernetes_namespace]
          target_label: namespace
        - source_labels: [__meta_kubernetes_pod_name]
          target_label: pod
        - source_labels: [__meta_kubernetes_pod_container_name]
          target_label: container

    - job_name: 'otel-logs'
      static_configs:
        - targets:
            - localhost
          labels:
            job: otel-logs
            __path__: /var/log/logs.log

      pipeline_stages:
        - json:
            expressions:
              component: attributes.component
              metric_type: attributes.metric_type
              trace_id: traceId  
              span_id: spanId 
        - traceid:
            source: trace_id 

logLevel: debug
