apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
  labels:
    app: prometheus
data:
  prometheus.yml: |
    global:
      scrape_interval: 15s

    scrape_configs:
      - job_name: dice-service
        scrape_interval: 5s
        static_configs:
          - targets: ['otel-dice-service:9464']
