apiVersion: v1
kind: Service
metadata:
  name: trivy-operator
  namespace: logging
spec:
  ports:
    - port: 8080
      targetPort: 8080
      name: http
  selector:
    app.kubernetes.io/name: trivy-operator
